import Head from "next/head"
import styles from 'styles/Home.module.css';

export const Document = ({children}: {children: string | JSX.Element}) => {
    return <div className={styles.container}>
      <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,400;0,600;1,700&family=Gentium+Book+Basic:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main>
          {children}
      </main>
</div>
}