// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for footer documents */
interface FooterDocumentData {
  /**
   * main header field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.main_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  main_header: prismic.KeyTextField;
  /**
   * name field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField;
  /**
   * professional title field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: pl. "boszorkánymester"
   * - **API ID Path**: footer.professional_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  professional_title: prismic.KeyTextField;
  /**
   * name placeholder field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.name_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name_placeholder: prismic.KeyTextField;
  /**
   * name field error message field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.name_field_error_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name_field_error_message: prismic.KeyTextField;
  /**
   * email placeholder field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email_placeholder: prismic.KeyTextField;
  /**
   * email field error message field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_field_error_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email_field_error_message: prismic.KeyTextField;
  /**
   * phone placeholder field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  phone_placeholder: prismic.KeyTextField;
  /**
   * service placeholder field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.service_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  service_placeholder: prismic.KeyTextField;
  /**
   * message placeholder field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.message_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  message_placeholder: prismic.KeyTextField;
  /**
   * message field error message  field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.message_field_error_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  message_field_error_message: prismic.KeyTextField;
  /**
   * checkbox statement field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.checkbox_statement
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  checkbox_statement: prismic.RichTextField;
  /**
   * checkbox error field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.checkbox_error
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  checkbox_error: prismic.KeyTextField;
  /**
   * send button text field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.send_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  send_button_text: prismic.KeyTextField;
  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice =
  | LargeParagraphSlice
  | DefaultParagraphSlice
  | BulletPointsSlice
  | SelectSlice;
/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, 'footer', Lang>;
/** Content for homepage documents */
interface IndexPageV2DocumentData {
  /**
   * hero field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.hero[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  hero: prismic.GroupField<Simplify<IndexPageV2DocumentDataHeroItem>>;
  /**
   * content header field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.content_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  content_header: prismic.KeyTextField;
  /**
   * pricelist button text field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.pricelist_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  pricelist_button_text: prismic.KeyTextField;
  /**
   * service group field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.service_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  service_group: prismic.GroupField<
    Simplify<IndexPageV2DocumentDataServiceGroupItem>
  >;
}
/**
 * Item in homepage → hero
 *
 */
export interface IndexPageV2DocumentDataHeroItem {
  /**
   * quote text field in *homepage → hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ide írd az idézet
   * - **API ID Path**: index_page_v2.hero[].quote_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote_text: prismic.RichTextField;
  /**
   * quote author field in *homepage → hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ide meg az elkövető nevét
   * - **API ID Path**: index_page_v2.hero[].quote_author
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  quote_author: prismic.KeyTextField;
}
/**
 * Item in homepage → service group
 *
 */
export interface IndexPageV2DocumentDataServiceGroupItem {
  /**
   * service_name field in *homepage → service group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.service_group[].service_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  service_name: prismic.KeyTextField;
  /**
   * service description field in *homepage → service group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: röviden, mert nem fog kifé
   * - **API ID Path**: index_page_v2.service_group[].service_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  service_description: prismic.KeyTextField;
  /**
   * lean more button text field in *homepage → service group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.service_group[].lean_more_button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  lean_more_button_text: prismic.KeyTextField;
  /**
   * sublink field in *homepage → service group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page_v2.service_group[].sublink
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sublink: prismic.KeyTextField;
}
/**
 * homepage document from Prismic
 *
 * - **API ID**: `index_page_v2`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexPageV2Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IndexPageV2DocumentData>,
    'index_page_v2',
    Lang
  >;
export type AllDocumentTypes = FooterDocument | IndexPageV2Document;
/**
 * Item in BulletPoints → Items
 *
 */
export interface BulletPointsSliceDefaultItem {
  /**
   * point field in *BulletPoints → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_points.items[].point
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  point: prismic.RichTextField;
}
/**
 * Default variation for BulletPoints Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BulletPointsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<BulletPointsSliceDefaultItem>
>;
/**
 * Slice variation for *BulletPoints*
 *
 */
type BulletPointsSliceVariation = BulletPointsSliceDefault;
/**
 * BulletPoints Shared Slice
 *
 * - **API ID**: `bullet_points`
 * - **Description**: `BulletPoints`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BulletPointsSlice = prismic.SharedSlice<
  'bullet_points',
  BulletPointsSliceVariation
>;
/**
 * Primary content in LeftInfoDefaultParagraph → Primary
 *
 */
interface DefaultParagraphSliceDefaultPrimary {
  /**
   * text field in *LeftInfoDefaultParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: default_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for LeftInfoDefaultParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DefaultParagraphSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DefaultParagraphSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *LeftInfoDefaultParagraph*
 *
 */
type DefaultParagraphSliceVariation = DefaultParagraphSliceDefault;
/**
 * LeftInfoDefaultParagraph Shared Slice
 *
 * - **API ID**: `default_paragraph`
 * - **Description**: `DefaultParagraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DefaultParagraphSlice = prismic.SharedSlice<
  'default_paragraph',
  DefaultParagraphSliceVariation
>;
/**
 * Primary content in HighlightedParagraph → Primary
 *
 */
interface LargeParagraphSliceDefaultPrimary {
  /**
   * text field in *HighlightedParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for HighlightedParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LargeParagraphSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LargeParagraphSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HighlightedParagraph*
 *
 */
type LargeParagraphSliceVariation = LargeParagraphSliceDefault;
/**
 * HighlightedParagraph Shared Slice
 *
 * - **API ID**: `large_paragraph`
 * - **Description**: `LargeParagraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LargeParagraphSlice = prismic.SharedSlice<
  'large_paragraph',
  LargeParagraphSliceVariation
>;
/**
 * Item in ServiceSelect → Items
 *
 */
export interface SelectSliceDefaultItem {
  /**
   * option field in *ServiceSelect → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Szolgáltatás neve
   * - **API ID Path**: select.items[].option
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  option: prismic.KeyTextField;
}
/**
 * Default variation for ServiceSelect Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SelectSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<SelectSliceDefaultItem>
>;
/**
 * Slice variation for *ServiceSelect*
 *
 */
type SelectSliceVariation = SelectSliceDefault;
/**
 * ServiceSelect Shared Slice
 *
 * - **API ID**: `select`
 * - **Description**: `Select`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SelectSlice = prismic.SharedSlice<'select', SelectSliceVariation>;
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FooterDocument,
      IndexPageV2DocumentData,
      IndexPageV2DocumentDataHeroItem,
      IndexPageV2DocumentDataServiceGroupItem,
      IndexPageV2Document,
      AllDocumentTypes,
      BulletPointsSliceDefaultItem,
      BulletPointsSliceDefault,
      BulletPointsSliceVariation,
      BulletPointsSlice,
      DefaultParagraphSliceDefaultPrimary,
      DefaultParagraphSliceDefault,
      DefaultParagraphSliceVariation,
      DefaultParagraphSlice,
      LargeParagraphSliceDefaultPrimary,
      LargeParagraphSliceDefault,
      LargeParagraphSliceVariation,
      LargeParagraphSlice,
      SelectSliceDefaultItem,
      SelectSliceDefault,
      SelectSliceVariation,
      SelectSlice,
    };
  }
}
