// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

const components = {
  bullet_points: dynamic(() => import('./BulletPoints')),
  default_paragraph: dynamic(() => import('./LeftInfoDefaultParagraph')),
  large_paragraph: dynamic(() => import('./HighlightedParagraph')),
  select: dynamic(() => import('./ServiceSelect')),
};

export default components;
