// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bullet_points: dynamic(() => import("./BulletPoints")),
  default_paragraph: dynamic(() => import("./LeftInfoDefaultParagraph")),
  faq_topic: dynamic(() => import("./FaqTopic")),
  large_paragraph: dynamic(() => import("./HighlightedParagraph")),
  listing: dynamic(() => import("./Listing")),
  select: dynamic(() => import("./ServiceSelect")),
  service_and_price: dynamic(() => import("./ServiceAndPrice")),
  social_link: dynamic(() => import("./SocialLink")),
  text_with_heading_and_highlighted_paragraphs: dynamic(
    () => import("./TextWithHeadingAndHighlightedParagraphs")
  ),
  text_with_headings: dynamic(() => import("./TextWithHeadings")),
};
