import Head from 'next/head';

import { IndexPageV2Document } from 'prismicio-types.js';
import WhatICanHelpYouWith from 'components/WhatICanHelpYouWith/organisms/WhatICanHelpYouWith';
import Hero from 'components/organisms/Hero';
import styles from 'styles/Home.module.css';

// @ts-ignore
// eslint-disable-next-line import/extensions
import { createClient } from '../prismicio.ts';

interface HomeProps {
  page: IndexPageV2Document
}

export default function Home({ page }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero content={page.data.hero} />
        <WhatICanHelpYouWith
          contentHeader={page.data.content_header}
          priceListButtonText={page.data.pricelist_button_text}
          serviceGroups={page.data.service_group}
        />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const client = createClient();
  const page = await client.getByUID('index_page_v2', 'index');

  return {
    props: { page },
  };
}
