import Head from 'next/head';

import WhatICanHelpYouWith from 'components/WhatICanHelpYouWith/organisms/WhatICanHelpYouWith';
import NavBar from 'components/NavBar/organisms/NavBar';
import Hero from 'components/organisms/Hero';
import styles from 'styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,400;0,600;1,700&family=Gentium+Book+Basic:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <NavBar />
        <Hero />
        <WhatICanHelpYouWith />
      </main>
    </div>
  );
}
